version: '3.8'

networks:
  techsecure_net:
    driver: bridge

services:
  db:
    image: mysql:8.0
    container_name: techsecure_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootrootpass
      MYSQL_DATABASE: techsecure_db
      MYSQL_USER: techuser
      MYSQL_PASSWORD: techpass
    volumes:
      
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - techsecure_net
    # Sécurité Docker : Le port de la BDD n'est pas exposé à l'extérieur, seul le conteneur Flask y accède

  web:
    build: ./app
    container_name: techsecure_web_container
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=techuser
      - DB_PASSWORD=techpass
      - DB_NAME=techsecure_db
    depends_on:
      - db
    networks:
      - techsecure_net
